### ISSUE TITLE
Clarify the definition of Taxonomic Units

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#10]
In CDAO, [`obo:CDAO_0000138`](http://purl.obolibrary.org/obo/CDAO_0000138) (taxonomic units or TUs) are defined as:

> A unit of analysis that may be tied to a node in a tree and to a row in a character matrix. It subsumes the traditional concepts of 'OTU' and 'HTU'.

I propose we modify this definition to:
> A subset of a [dwc:Taxon](https://terms.tdwg.org/wiki/dwc:Taxon). TUs may be as broad as a entire taxon or as specific as a single organism ([obo:OBI_0100026](http://purl.obolibrary.org/obo/OBI_0100026)).

A competency question for this interpretation of this term is "what taxon or subset of a taxon does a particular node on a phylogeny represent?"

I propose we import this term into the Phyloref Ontology and give it another definition to make it clear how we plan to use this term in our ontology. This issue is for tracking this import. We could also propose this change to CDAO or just import it unchanged and make our interpretation of this term clear in the Phyloreferencing Specification.

**Comment by hlapp** [comment]
I really don't see the need to or benefit from tying the concept that strongly to `dwc:Taxon` (which has lots of issues, not the least of which it's exceedingly squishy _definition_).

If we are going to use the class in certain ways it's easy to annotate that through comments (or more specific IAO attributes).

The only counterargument would be if we were to use the concept in a way that's evidently in conflict with its definition. But I don't see that.

**Comment by hlapp** [comment]
The TCAN ontology formalizes the alignment between classes in different ontologies and vocabularies that represent a taxon concept. This includes `dwc:Taxon`, `tc:TaxonConcept`, and openbiodiv:TaxonomicConcept. See #28.

This alignment may need future amendment, but I think this issue can be closed once #28 is merged.
