### ISSUE TITLE
An object property for indicating taxonomic units involved in a Taxonomic Unit match

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#11]
Proposed term: `matches_taxonomic_unit` (class)
Definition: Indicates a taxonomic unit that is involved in a Taxonomic Unit match
Domain: A taxonomic unit match (#9)
Range: A taxonomic unit (#10)
See also: [scratch ontology](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/ontologies/phyloref_testcase.owl#L172), [PHYX context](https://github.com/phyloref/clade-ontology/blob/master/testcase2owl/paper-context.json#L225)

Competency questions:
* Which taxonomic units does a taxonomic unit match assert as overlapping with each other?

**Comment by hlapp** [comment]
It seems like a TUMatch instance would link two TU instances with the semantics that there is some kind of match between them, and properties further qualifying the nature of the match.

Given that, having _matches_ semantics expressly in the property linking the TUMatch instance to TU instances seems wholly redundant.

More generally, we really need much stronger competency questions, in that they need not only demonstrate that the link they create is worth navigating, but that a more generic property _will not do_. So for example, the competency question does not answer why `cdao:references_TU` will not do. The default has to be to _not_ create a new property (or class) and reuse what's already there.

**Comment by gaurav** [comment]
I see what you mean! We can't use [`cdao:represents_TU`](http://purl.obolibrary.org/obo/CDAO_0000187) (#6) as currently defined, since it is defined to only relate nodes to TUs, but we could broaden the definition. However, given that it specifically refers to entities *representing* TUs, I don't think we should use it for TUMatches, as they don't "represent" TUs.

Instead, I think it would be better to say that the TUs are [`part_of`](http://purl.obolibrary.org/obo/BFO_0000050) a TUMatch, i.e. to say that TUMatches are composed of TUs. The competency question would then be, "Which taxonomic units compose a particular taxonomic unit match?". Would that make sense?

**Comment by hlapp** [comment]
> Instead, I think it would be better to say that the TUs are part_of a TUMatch, i.e. to say that TUMatches are composed of TUs.

But wouldn't that make it difficult to say how these parts of the TUMatch are unequal? I.e., this would perhaps work fine if we can assume that we don't need to qualify the strength, confidence etc of each (or some) TU being part of the match. I thought that therefore each TUMatch would reference only a single TU.

**Comment by hlapp** [comment]
So there's a `matches_TU` property in the Phyloref ontology now (albeit without label or definition yet). It's asserted as a superproperty of `cdao:represents_TU`. There's no domain constraint (nor do I think there should or needs to be one). @gaurav would that address this issue?

**Comment by gaurav** [comment]
Yes, I think that would work! Especially since the definitions for `includes_TU` and `excludes_TU` already includes property chains that should allow the reasoner to use a matched TU in place of the represented TU. I've opened an issue in Phyx.js at https://github.com/phyloref/phyx.js/issues/97 to try this out.

**Comment by hlapp** [comment]
As of today we decided to close this issue due to lack of a supporting use-case. Once a use-case does surface, we'll reopen it.
