### ISSUE TITLE
An object property for indicating specimens included in a taxonomic unit

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#12]
Proposed term: `includes_specimen`
Definition: Indicates a specimen that is included in a Taxonomic Unit (#10). A taxonomic unit may consist of a set of taxa as well as a set of specimens without asserting that those specimens necessarily belong to one of those taxa, only that they are all included in the taxonomic unit.
Domain: Taxonomic Unit (#10)
Range: dwc:Token in [Semantic Darwin Core](http://www.semantic-web-journal.net/system/files/swj1213.pdf)
See also: [scratch ontology](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/ontologies/phyloref_testcase.owl#L133), [PHYX context](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/testcase2owl/paper-context.json#L167)

Competency questions:
* Which specimens are explicitly included in a taxonomic unit?

**Comment by hlapp** [comment]
Is this different from something like _has_specimen_? It sounds like the domain of connecting specimens to TUs should already be covered by vocabularies or ontologies out there from the biodiversity informatics realm.

**Comment by gaurav** [comment]
Some relevant ontologies (e.g. Biological Collections Ontology, Semantic Darwin Core) separate this into three entities: an [Identification](http://purl.obolibrary.org/obo/BCO_0000084), which relates an [organismal entity](http://www.ontobee.org/ontology/BCO?iri=http://purl.obolibrary.org/obo/PCO_0000031) (via [`of organism`](http://purl.obolibrary.org/obo/BCO_0000086)) to a [Taxon](http://www.ontobee.org/ontology/BCO?iri=http://rs.tdwg.org/dwc/terms/Taxon) (via [`to taxon`](http://purl.obolibrary.org/obo/BCO_0000085)). We could use that approach here, where we assert an identification of a particular specimen to be a particular taxonomic unit. The competency question would be, "Which specimens have been identified as belonging to this taxonomic unit?"

**Comment by hlapp** [comment]
> The competency question would be, "Which specimens have been identified as belonging to this taxonomic unit?"

BTW you're still not understanding competency questions. I.e., you're still proposing the term or property first, and then invent a trivial question that uses it. If there's valid competency question then it does not change from one implementation that potentially achieves it to another. The competency question is the starting point, really.

For our project, a valid competency question (for developing the ontology) is one motivated and necessitated by one or more goals of our project that is impossible or difficult to achieve by _not_ using the ontology to start with.

**Comment by hlapp** [comment]
@gaurav can you comment whether this is remains a problem that needs solving? I don't think this is (or was) among our latest list of former testcase vocabulary  properties that need a more permanent home.

**Comment by gaurav** [comment]
Yup, we now represent specimens entirely as logical expressions, and so we don't need new object properties for it. Closing.
