### ISSUE TITLE
A class for a PHYX study

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#14]
Proposed term: `PHYXStudy` (class)
Subclass of: [document](http://purl.obolibrary.org/obo/IAO_0000310)
Definition: A study consists of a set of phyloreferences as well as a set of phylogenies that can be used to test those phyloreferences. A PHYX file consists of a single PHYX study and are usually derived from a single publication or a small number of publications (e.g. if the phyloreferences are published in one paper based on phylogenies published in another).

Competency questions:
* Which phylogenies can be used to test a particular set of phyloreferences?

Currently referred to as a [PhyloreferenceTestCase](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/ontologies/phyloref_testcase.owl#L279), but I think "PHYX Study" is a better term.

**Comment by hlapp** [comment]
Is this different from an attribute connecting a phyloreference instance to a phylogeny?

**Comment by gaurav** [comment]
I see this as a representation of the PHYX study itself in RDF, though perhaps it's not necessary to define it in OWL. Instances of this class would assert that a group of phylogenies and a group of phyloreferences were grouped together by an author, and would have annotations reflecting authorship, publication status, and so on. In which case, a better competency question might be, "Which phylogenies and phyloreferences are included in a particular study?". This isn't very useful for the Ontology of Phyloreferences, though, so in retrospect it probably isn't worth including in the Phyloref Ontology either.

We do need a term for asserting that a curator expects a Phyloreference to resolve to a particular Node (#26). If we had such a term, then the Tree within which that Node is located must be a reference phylogeny for the phyloreference, and so would act as an attribute connecting a phyloreference instance to a phylogeny. I think that would be useful to include in the Ontology of Phyloreferences.

**Comment by hlapp** [comment]
You are using _Ontology of Phyloreferences_ in two places above, but we have obsoleted this term because it is confusing. Case in point, I think in the first instance you mean _Clade Ontology_, but it seems in the second instance you may actually mean _Phyloreferencing Ontology_?

**Comment by hlapp** [comment]
And why can't we simply use [IAO:document](http://purl.obolibrary.org/obo/IAO_0000310)? I think to justify being defined as a subclass of that, the definition will have to follow the genus-differentia pattern. I.e., _An instance of PHYXStudy is an IAO:document that ..._, followed by qualifying how PHYXStudy documents can be distinguished from all other IAO:document instances. Then this still needs to be followed by an argument as to how that differentia is valuable to and matters for our goals.

**Comment by hlapp** [comment]
I'm unclear what the open issue here is. It seems that the relationship between a phyloreference and a study from which it was curated is one of provenance (such as [`prov:wasDerivedFrom`](https://www.w3.org/TR/prov-o/#wasDerivedFrom)) (see #16), and that between a phyloreference and a reference phylogeny is one of supporting evidence (see #15).

**Comment by gaurav** [comment]
The original idea here was to model the PHYX file itself -- as a collection of related phyloreferences and phylogenies -- but linking phyloreferences to the document they were published in with `prov:wasDerivedFrom` and to their reference phylogenies with [`has evidence`](http://purl.obolibrary.org/obo/RO_0002558) should provide all the information we need. Closing this issue.
