### ISSUE TITLE
An object property for listing phylogenies in a PHYX Study

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#15]
Proposed term: `has_phylogeny`
Definition: Indicates a phylogeny included in a PHYX Study (#14).
Domain: PHYX Study (#14)
Range: Tree ([`obo:CDAO_0000110`](http://purl.obolibrary.org/obo/CDAO_0000110))
See also: [scratch ontology](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/ontologies/phyloref_testcase.owl#L75), [PHYX context](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/testcase2owl/paper-context.json#L48)

Competency questions:
* Which phylogenies are included in a PHYX study?

We previously supported "phylogeny groups", which consisted of multiple phylogenies grouped together for some reason (such as because they were imported from a single file). However, it probably makes more sense for PHYX files to have a simple list of phylogenies, where phylogenies can be individually labeled to indicate different sources.

**Comment by hlapp** [comment]
Are we talking about (JSON) keys in a PHYX file, or properties in an ontology? It seems to me this should be in the former category.

**Comment by gaurav** [comment]
You're right: we need this term to ensure that phylogenies are retained during the JSON-LD to RDF conversion for PHYX files, but they don't serve any value within the ontology itself. #26 will provide a better link between phyloreferences and phylogenies (via their Nodes). Should we close this term request?

**Comment by hlapp** [comment]
> Should we close this term request?

Perhaps so. I'll go ahead and close it.
