### ISSUE TITLE
A datatype property for the Newick representation of a phylogeny

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#17]
Proposed term: `as_newick_string`
Definition: The [Newick representation](https://en.wikipedia.org/wiki/Newick_format) of a particular phylogeny.
Domain: Tree ([`obo:CDAO_0000110`](http://purl.obolibrary.org/obo/CDAO_0000110))
Range: [xsd:string](https://www.w3.org/TR/xmlschema11-2/#string)
See also: [scratch ontology](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/ontologies/phyloref_testcase.owl#L203), [PHYX context](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/testcase2owl/paper-context.json#L102)

Competency questions:
* What is the Newick representation of a particular phylogeny?

**Comment by hlapp** [comment]
Please provide a less trivial competency question. If you can't come up with one, then at least add why this question has to be answerable using the ontology.

**Comment by hlapp** [comment]
The revised Phyloref ontology in #29 proposes that this be an AnnotationProperty `phyloref:newick_expression`.

There is currently no good use-case or competency question supporting for what inference or query reasoning over this property is required.

**Comment by gaurav** [comment]
Agreed! Implementation will occur as part of the ticket at phyloref/phyx.js#4.
