### ISSUE TITLE
Translate ontology into OWL Functional Syntax with a workflow for generating RDF/XML

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#24]
The authoritative development version of `./phyloref.owl` should be stored as an OWL Functional Syntax file and renamed to `./phyloref.ofn`. This will make it easier to compare diffs of this file when changing it during development.

The canonical version of this file (`/docs/phyloref.owl`) should remain in RDF/XML. We should create a workflow for generating this file from the OWL Functional Syntax development version at release time. Note that the OWLAPI default export in the OWL Functional Syntax doesn't include the version number of the sofware used to generate that file, so we will need to add that in manually.

**Comment by hlapp** [comment]
Initial conversion to .ofn was part of #27, and automated release process is in #30.
