### ISSUE TITLE
Possible error in a propertyChainAxiom in excludes_lineage_to 

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#4]
Recent versions of JFact (I've tested 4.x and 5.x) cannot reason over the Phyloreferencing ontology. I reported this to JFact last October, and was told that the reasoning error was because of a property chain axiom in `excludes_lineage_to` that is invalid (https://github.com/owlcs/jfact/issues/19#issuecomment-336639215).

This isn't holding up development for now, since the ontology reasons fine in JFact 1.2.4, but fixing this might help us speed up reasoning with more advanced reasoners.

**Comment by hlapp** [comment]
I suppose a property chain with one element should be a sub-property axiom instead.
