### ISSUE TITLE
An object property for associating an internal specifier with a phyloreference

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#7]
Proposed term: `has_internal_specifier` (object property)
Definition: Associates an internal specifier with a phyloreference.
Domain: Phyloreference
Range: Specifier
See also: [scratch ontology](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/ontologies/phyloref_testcase.owl#L55), [PHYX context](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/testcase2owl/paper-context.json#L82)

Competency questions:
* Which specifiers does a particular phyloreference have that should be included in the denoted clade.
* Does a particular phyloreference have any specifiers that are to be included in the clade?

**On hold** until we resolve https://github.com/phyloref/phyloref-ontology/issues/8#issuecomment-391907602

**Comment by hlapp** [comment]
See [comment on #8](https://github.com/phyloref/phyloref-ontology/issues/8#issuecomment-386127992) re: supporting competency question(s).

**Comment by hlapp** [comment]
See other [comment on #8](https://github.com/phyloref/phyloref-ontology/issues/8#issuecomment-387737382), which applies here too. Including in particular my skepticism about there being no superproperty.

**Comment by gaurav** [comment]
**On hold** until we resolve https://github.com/phyloref/phyloref-ontology/issues/8#issuecomment-391907602

**Comment by hlapp** [comment]
In light of the conclusion from recent discussions that at least for purposes of phylogenetic clade definitions there is no discernible difference between a specifier and a referent to a taxon concept, this should be closed. See also https://github.com/phyloref/phyloref-ontology/issues/8#issuecomment-448387121.

Also, #29 introduces and proposes `phyloref:includes_TU` for signifying a TU to be included in a clade.

**Comment by gaurav** [comment]
Agreed: `phyloref:includes_TU` is pretty much exactly what this issue was going for! Closing.
